apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: ingress-status-exporter
  labels:
    app: ingress-status-exporter
spec:
  selector:
    app: ingress-status-exporter
  type: ClusterIP
  ports:
  - name: http-metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
